version: '3'
services:
    axondb:
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: secret
    middleware:
        image: "dxfrontiers/axon-state-machine:latest"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://axondb:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=secret
        depends_on:
           - axondb

